feat: 메뉴 상세 페이지 최종 디자인 적용
prgrms-web-devcourse/Team-Tasty-Masiottae-FE pull request #134
Opened 2022-08-07 12:48 UTC by chogyejin

## ✅ 이슈 번호
#133 
## 📌 기능 설명
메뉴 상세 페이지 최종 디자인 적용

## 👩‍💻 요구 사항과 구현 내용
- 피그마에는 이미지와 그 아래 컨테이너가 화면에 꽉차도록 그려져있는데.. 기본 레이아웃 흐름에 맞춰서 좌우 padding을 갖고 있어서 해결이 안되어 패딩이 있는 상태로 적용했습니다.
- 맛 태그들은 일단 기존의 Tag 컴포넌트와 동작이 다른 것이 있어서 스타일을 유사하게 직접 만들어 넣어뒀습니다.
- Input을 4.8rem 혹은 5.6rem으로 설계해주셨는데, 위아래 padding 계산과 안의 content의 가운데 정렬이 힘들어 일단 4rem으로 만들었는데, 바꿔야할 것 같다면 의견 주시면 감사하겠습니다.
## 구현 결과

<img width="1440" alt="스크린샷 2022-08-07 21 42 26" src="https://user-images.githubusercontent.com/81501723/183291189-5768af5e-a441-483a-b0f3-7117ac50f6fd.png">
<img width="1440" alt="스크린샷 2022-08-07 21 42 22" src="https://user-images.githubusercontent.com/81501723/183291193-4be1eb24-6105-4475-917f-ae0fdf7ca55c.png">

2022-08-07 16:59 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
> +      <Image src={menu.image} alt="" />
```js
      <ImageContainer>
        <Image src={menu.image} alt="" />
      </ImageContainer>
```
이런식으로 div로 감싼 다음 해당 div에 `margin-left: -2rem;
  margin-right: -2rem;` 스타일을 적용하면 화면에 꽉차게 표현이 가능합니다 😊

2022-08-07 17:30 UTC, bellasimi approved these changes
- 그리고 모달 아이콘의 크기가 맞지 않아 이 부분도 수정이 필요해보입니다. 
- 수정 아이콘의 경우 현재 2.5rem인데, 2rem 정도로 맞추면 괜찮아 보이네요 👀

![image](https://user-images.githubusercontent.com/79133602/183303424-797e23dd-424d-4803-87f3-5995c44bc601.png)

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
>        <Footer>
Footer가 없어도 style이 잘 되는군요 👀 Footer라는 태그명도 현재 전체의 footer 위치가 아니라 적절하지 않은 것 같습니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
> +`
`width: 100%`를 지우고 `margin-left: -2rem; margin-right: -2rem;` 를 적용해야 원하는 모습이 나오는 것 같네요

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
>  `
Header가 피그마에 나온 것보다 더 아래에 있군요. `  margin-top: -1.5rem;` 정도로 바꾸면 어떨까요?

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
> +`
디자인 시안처럼 보이기 위해 해당 부분을 좀더 올려야 될 것 같습니다.`top: -2rem;`

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
> +const EmptyHeart = styled(AiOutlineHeart)`
현재 하트와 dot사이가 디자인 보다 멀기 때문에 `margin-right: -1rem;`를 추가해야 할 것 같습니다.

아래 Heart 역시 동일합니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
> +const LikesCountText = styled.span<{ clicked: boolean }>`
Heart의 위치를 옯겨서 얘도 `right: 1.5rem`으로 바꿔주셔야 할 것 같습니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
>    padding: 1rem;
현재 디자인 시안엔 padding이 없고, avartar로 부터 일정 수준 떨어져야 하기에 `  padding: 1rem;`를 빼고 `margin-top: 1rem;`를 추가해야 될 것 같습니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentInput.tsx
>    }, [])
useEffect는 없어도 될 것 같습니다. 👀 아래처럼 처리하면 textArea가 잘 계산이 되서 나옵니다. 

```js
const TEXTAREA_HEIGHT = '4.8rem'
const TEXTAREA_HEIGHT_PX = 48
const handleResizeInputHeight = useCallback(
    (e: ChangeEvent<HTMLTextAreaElement>) => {
      const { value } = e.target

      if (textareaRef.current === null) {
        return
      }

      if (value === '') {
        textareaRef.current.style.height = TEXTAREA_HEIGHT
      }

      const isScrollLess =
        Number(textareaRef.current.scrollHeight) < TEXTAREA_HEIGHT_PX
      textareaRef.current.style.height = isScrollLess
        ? TEXTAREA_HEIGHT
        : textareaRef.current.scrollHeight + 'px'

      setComment(e.target.value)
    },
    [textareaRef]
  )
```

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentInput.tsx
>    return (
Textarea onChange시 `handleChange`라는 함수명도 좋지만 해당 이벤트 시 높이 조절을 하는 게 목적인 함수인 만큼 좀 더 직관적인 이름을 쓰는 게 좋을 것 같습니다. `handleResizeInputHeight`

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentInput.tsx
>    width: 100%;
style을 다음과 같이 봐꾸면 원하는 결과를 보실 수 있을 것 같습니다. 
 ``` 
  height: 4.8rem;
  font-size: 1.8rem;
  padding: 1.4rem 8rem 1.3rem 2rem;
```

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentInput.tsx
>  const AddCommentButton = styled.button`
버튼 역시 다음 부분의 style을 변경하면 원하는 결과를 얻을 수 있을 것 같습니다. 
```
 bottom: 0.7rem;
  right: 0.7rem;
  width: 6rem;
  height: 3.5rem;
  color:  ${(props) => props.theme.color.mainWhite};
  background-color: ${(props) => props.theme.color.mainBlack};
```

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/MenuDetail.tsx
> +          <Modal
Modal은 고정된 위치에서 나오기 때문에 여기에 위치할 필요가 없지 않나요? 아예 밑으로 빼는게 가독성이 좋을 것 같습니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentList.tsx
>        {commentList.map(({ id, author, createdAt, comment }) => (
현재 반복문 만큼 모달이 나타나고 있습니다. comment dot을 눌렀을 때 하나의 모달만 나오게 하기 위해 반복문 밖에 Modal 두면 좋겠습니다 😊

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentList.tsx
CommnetCountText에 `font-weight: 700;`를 추가해야 될 것 같습니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentList.tsx
> +  margin-left: 1rem;
댓글 간 간격 여유를 주기 위해 `padding-bottom: 0.7rem;` 정도를 주면 좋을 것 같습니다.

2022-08-07 17:30 UTC, bellasimi commented on src/components/detail/CommentList.tsx
>  `
지금 보니 DateText의 글자가 작은데 의도하신걸까요? 아니라면 색상과 함께 아래처럼 수정할 필요가 있어보입니다. 
  ```
  font-size: 1.2rem;
  color: ${(props) => props.theme.color.fontLight};
  ```

2022-08-07 17:38 UTC, bellasimi commented on src/utils/getDate.ts
코드가 간결하고 좋군요 👍👍

2022-08-07 17:41 UTC, bellasimi requested changes
수고하셨습니다. 계진님 😊 코드 리뷰 반영 후 알려주시면 approved 바로 날리겠습니다. 혹시 뭔가 의문이 있다면 슬랙 주세요

2022-08-07 20:34 UTC, nyoung113 commented on src/components/detail/MenuDetail.tsx
> +      <Image src={menu.image} alt="" />
width에 calc(100% + 4rem)해도 맞습니다! 저는 이 방법대로 했네요!

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/CommentInput.tsx
>    return (
해당 컴포넌트에 change event에 대한 핸들러가 따로 없으면 간결하게 적는 걸 선호하는 편입니다. 컴포넌트 Props를 그냥 Props로 받는 것처럼요!

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/CommentInput.tsx
>    }, [])
useEffect를  제거했습니다!

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/CommentInput.tsx
>    width: 100%;
input height 5.6rem + font-size 1.8rem 이고 input height 4.8rem + font-size 1.6rem 아닌가요?

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/CommentList.tsx
>        {commentList.map(({ id, author, createdAt, comment }) => (
반영해서 문제 해결했습니다!

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/CommentList.tsx
> +  margin-left: 1rem;
0.8로 처리했습니다!

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/CommentList.tsx
>  `
전 브랜치에서 작업한줄 알았는데 여기에 반영이 안 되어 있네요 적용하겠습니다! 근데 theme color에 대해서 생각해봤는데, theme이 변할 때만 변하는 요소에만 theme color를 적용하고 theme이 변해도 유지되는 요소는 정적인 color를 사용해도 되지 않나요?

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/MenuDetail.tsx
> +      <Image src={menu.image} alt="" />
다들 감사합니다!

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/MenuDetail.tsx
>        <Footer>
footer를 제거하고 UserWrapper에 margin을 주었습니다~

2022-08-08 01:53 UTC, chogyejin commented on src/components/detail/MenuDetail.tsx
>  `
적용했습니다~

2022-08-08 03:50 UTC, bellasimi commented on src/components/detail/CommentList.tsx
>  `
혹시 나중에 변경되는 경우를 대비했는데 저희는 현실적으로 변경될 거 같지 않으니 그녕 색상을 쓰셔도 좋습니다

2022-08-08 03:50 UTC, bellasimi approved these changes

2022-08-08 08:36 UTC, merged