refactor: input validation 처음 렌더링 시 없앰/ 가격 단위 추가
prgrms-web-devcourse/Team-Tasty-Masiottae-FE pull request #258
Opened 2022-08-30 06:09 UTC by nyoung113

## ✅ 이슈 번호
resolve #243 
resolve #244
## 📌 기능 설명

## 👩‍💻 요구 사항과 구현 내용
- input validation이 처음 나타날 때 validation을 하지 않도록 합니다.

```js
  const [isInit, setIsInit] = useState({
    franchise: true,
    title: true,
    originalTitle: true,
    optionList: true,
    expectedPrice: true
  })
```
init State를 만들고 각 handler에서 false로 바꿔주는 방식을 사용했습니다.

```js
const handleTitleChange = (e: React.FormEvent<HTMLInputElement>) => {
    title = e.currentTarget.value
    setIsInit((isInit) => {
      return { ...isInit, title: false }
    })
    handleOnChange()
  }
```

- 가격을 100만원 미만(99만원)까지 적용하고, 숫자 단위 형식으로 바꿨습니다.(3자리 수 컴마)

## 구현 결과

2022-08-30 07:51 UTC, bellasimi commented on src/components/create-menu/InputList.tsx
> +              ? expectedPrice.toLocaleString('ko-KR')
toLocaleString으로 간단히 구현하셨군요 👍

2022-08-30 07:57 UTC, bellasimi commented on src/components/create-menu/InputList.tsx
> +
저 같은 경우엔 error state를 객체형으로 만들고 error.franchise에 franchise 에러시 에러 메시지를 setState 했습니다. 그리고 error.franchise가 !==''일 때만 에러메시지를 출력하게 해서 처리했네요 👀

2022-08-30 08:00 UTC, bellasimi commented on src/components/create-menu/InputList.tsx
> +            }
(option.name && option.description
                ? true
                : false) || isInit.optionList 였을 까요? 지금 이 부분이 잘 작동하지 않는 것 같아요

2022-08-30 08:00 UTC, bellasimi requested changes
현재 optionList의 isValid 초기값이 여전히 false로 나오고 있군요 👀 그 부분 해결시면 될 것 같습니다.

2022-09-01 04:45 UTC, nyoung113 commented on src/components/create-menu/InputList.tsx
> +            }
아 이부분은 optionList 안에 또 배열로 만들어서 각각 하나의 input마다 따로 처리를 해줘야 하네요..! 이 부분이 필요한지는 다시 이야기해봐야 할 것 같습니다!

2022-09-04 13:15 UTC, bellasimi approved these changes
확인했습니다.

2022-09-05 03:39 UTC, merged